# Generated by Django 4.2.3 on 2023-08-10 19:33

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_type_auction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=timezone.now()),
        ),
    ]
