# Generated by Django 4.2.3 on 2023-08-10 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.CharField(default=datetime.datetime(2023, 8, 10, 21, 39, 5, 394582), max_length=64),
        ),
    ]
