# Generated by Django 4.2.3 on 2023-08-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.CharField(max_length=64),
        ),
    ]
