# Generated by Django 4.2.3 on 2023-08-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='datetime',
        ),
    ]
