# Generated by Django 4.2.3 on 2023-08-10 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 19, 50, 4, 200869, tzinfo=datetime.timezone.utc)),
        ),
    ]
