# Generated by Django 4.2.3 on 2023-08-10 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 20, 3, 59, 977643, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.PositiveIntegerField(),
        ),
    ]
