# Generated by Django 4.2.3 on 2023-08-11 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_user_first_remove_user_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 16, 57, 11, 212916, tzinfo=datetime.timezone.utc)),
        ),
    ]
