# Generated by Django 4.2.3 on 2023-08-11 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auction_datetime_alter_bid_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='listed_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 17, 6, 5, 784095, tzinfo=datetime.timezone.utc)),
        ),
    ]
