# Generated by Django 4.2.3 on 2023-08-11 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auction_listed_by_alter_auction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 17, 7, 55, 969003, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='auction',
            name='listed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
