# Generated by Django 4.2.3 on 2023-08-12 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auction_datetime_alter_bid_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 14, 51, 11, 152385, tzinfo=datetime.timezone.utc)),
        ),
    ]
