# Generated by Django 4.2.3 on 2023-08-12 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_auction_datetime_alter_bid_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 14, 53, 23, 250352, tzinfo=datetime.timezone.utc)),
        ),
    ]
