# Generated by Django 4.2.3 on 2023-08-12 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_remove_user_money_alter_auction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 15, 4, 50, 420274, tzinfo=datetime.timezone.utc)),
        ),
    ]
