# Generated by Django 4.2.3 on 2023-08-13 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_alter_auction_datetime_alter_auction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 7, 24, 2, 65373, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(max_length=254),
        ),
    ]
