# Generated by Django 4.2.3 on 2023-08-13 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_alter_auction_datetime_alter_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='auction',
            name='watchlisted',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auctions.watchlist'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 9, 20, 10, 300072, tzinfo=datetime.timezone.utc)),
        ),
    ]
