# Generated by Django 4.2.3 on 2023-08-13 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_remove_watchlist_item_auction_watchlisted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 9, 26, 29, 588144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.BooleanField(),
        ),
    ]
